services:
  server:
    image: sist-mmla-para-prac:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
       PYTHON_VERSION: 3.12.6
       UID: 10001
    expose:
      - "8000"
    volumes:
      - .:/app
      - app_uploads:/app/code/static
      - app_cache:/app/.cache
      - whisper_models:/app/whisper_models
      - app_logs:/app/logs
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      WHISPER_CACHE_DIR: /app/whisper_models
      # - FIREBASE_API_KEY=tu_api_key
      # - FIREBASE_AUTH_DOMAIN=tu_auth_domain
      # - FIREBASE_DATABASE_URL=tu_database_url
      # - FIREBASE_PROJECT_ID=tu_project_id
      # - FIREBASE_STORAGE_BUCKET=tu_storage_bucket
      # - FIREBASE_MESSAGING_SENDER_ID=tu_messaging_sender_id
      # - FIREBASE_APP_ID=tu_app_id
    user: appuser
    networks:
    - app-network
    command: ["gunicorn", "-c", "/app/gunicorn.conf.py", "code.app:app"]

  nginx:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - app_logs:/app/logs
    - app_uploads:/app/code/static
    depends_on:
      - server
    networks:
      - app-network

volumes:
  app_uploads:
  app_cache:
  whisper_models:
  app_logs:

networks:
  app-network:
    driver: bridge